In [1]:
#IMPORTS
import numpy as np
import pandas

In [ ]:
# Execute this block for file input
INPUT_FILE_NAME = ""
""""
Expected format: Header followed by integers delimited by newlines.
"""
input_series = list(pandas.read_csv(INPUT_FILE_NAME))

In [ ]:
# Execute this block for user input
""""
Expected format : Numbers in an array delimited by comma
"""
input_series = [int(num) for num in input().split(",")]

In [9]:
#Custom function to generate adjacency matrix for the provided HVG
def adjacency_matrix(time_series):
  shape = len(time_series)
  output_matrix = np.zeros(
        shape = (shape, shape),
        dtype=int
    )
  input_array=time_series
  #Initializing the index variable
  init=0

#Code block to find the highest visible subsequent value in the array
  while init < shape:
    comparable = init+1
    while comparable < shape:
      if(input_array[init] < input_array[comparable]):
        output_matrix[init][comparable] = 1
        output_matrix[comparable][init] = 1
        break
      comparable=comparable+1
    init=init+1

#Code block to make all neighboring values True
  init = 1
  while init < shape:
    output_matrix[init-1][init] = 1
    output_matrix[init][init-1] = 1
    init=init+1

  return output_matrix


In [3]:
#Passing the user input as arguement to generate adjacency matrix.

print(adjacency_matrix(input_series))

#print(adjacency_matrix([10,15,5,10,15]))

[[0 1 0 0 0]
 [1 0 1 1 0]
 [0 1 0 1 0]
 [0 1 1 0 1]
 [0 0 0 1 0]]
[[0 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]
